### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by Voziv** [argocd-diff-action/argocd-diff-action#4]
I haven't had time to do an exact reproduction on a fresh argocd install, however either `ApplicationSet` or argocd `2.6.x` seems to have broken this action for ratehub.

```
Run ratehub/argocd-diff-action@v0
  with:
    argocd-server-fqdn: *** (dev instance, running v2.6.1)
    argocd-token: ***
    github-token: ***
    argocd-version: v2.6.1
    argocd-extra-cli-args: --grpc-web
```

When running the action I get `TypeError: Cannot read properties of undefined (reading 'source')`. It's not helpful in debugging what is going wrong. If it's a result of the api call I'd like to have the api call contents dumped.

I believe I've already added a bit more debug logs but some of them were not successful in dumping enough information.
